version: '3.9'
services:
  mariadb_206:
    container_name: mariadb_206
    hostname: mariadb_206
    image: mariadb:11.1
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mariadb_206:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: senha
      MARIADB_DATABASE: base_de_dados
      MARIADB_USER: usuario
      MARIADB_PASSWORD: senha
      TZ: America/Sao_Paulo
